orders/urls.py
from django.urls import path

from orders.views import (CanceledTemplateView, OrderCreateView,
                          OrderDetailView, OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order-succes/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from products.models import Basket
from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    REFUND = 4
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
        (REFUND, 'Возврат')
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ #{self.id}. {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        # 'placeholder': Order.initiator.first_name,
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        # 'placeholder': Order.initiator.last_name
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        # 'placeholder': Order.initiator.email,
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        # 'placeholder': 'Россия, Москва, ул. Мира, дом 6',
    }))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order
from products.models import Basket

stripe.api_key = settings.STRIPE_SECRET_KEY


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'Store - Заказы'
    queryset = Order.objects.all()
    ordering = ('-created',)

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - Заказ #{self.object.id}'
        return context


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'Store - Спасибо за заказ'


class CanceledTemplateView(TemplateView):
    template_name = 'orders/cancel.html'


class OrderCreateView(TitleMixin, CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'Store - Оформление заказа'

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_product(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_canceled')),
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return HttpResponse(status=HTTPStatus.BAD_REQUEST)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return HttpResponse(status=HTTPStatus.BAD_REQUEST)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
        )

        # line_items = session.line_items
        # Fulfill the purchase...
        fulfill_order(session)

        # Passed signature verification
    return HttpResponse(status=HTTPStatus.OK)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

orders/templates/orders/cancel.html
<!DOCTYPE html>
<html>
<head>
    <title>Checkout canceled</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>
</body>
</html>

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
    <section>
        <div class="alert alert-warning text-center" role="alert">
            Пожалуйста, заполните адрес электронной почты.
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Корзина</span>
                        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name }}</h6>
                                    <small class="text-muted">{{ basket.quantity }} шт.</small>
                                </div>
                                <span class="text-muted">{{ basket.sum | intcomma }} руб.</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Сумма к оплате</span>
                            <strong>{{ baskets.total_sum | intcomma }} руб.</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Адрес доставки</h4>
                    <form action="{% url 'orders:order_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной почты</label>
                                {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.address.id_for_label }}" class="form-label">Адрес</label>
                                {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказ №{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Кол-во</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Сумма</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in object.basket_history.purchased_items %}
                            <tr>
                                <th scope="row">
                                    {{ item.product_name }}
                                </th>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.price|intcomma }} руб.</td>
                                <td>{{ item.sum|intcomma }} руб.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Итого {{ object.basket_history.total_sum|intcomma }} руб.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказы</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Итого</th>
                            <th scope="col">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.created|naturaltime }}</td>
                                <td>{{ order.basket_history.total_sum|intcomma }} руб.</td>
                                <td>
                                    <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Ваш заказ успешно сформирован.
                            </h4>
                            <div class="text-center mt-4">
                                <a href="{% url 'index' %}">Вернуться на главную</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}