shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи {} перейдите по ссылке: {}'.format(
            self.user.email,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from users.models import User
from users.tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите фамилию'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите эл. почты'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Подтвердите пароль'
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-label'
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'image')

users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from users.models import EmailVerification, User


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Store - Авторизация'


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Поздравляем! Вы успешно зарегистрированы!'
    title = 'Store - Регистрация'


class UserProfileView(TitleMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Store - Личный кабинет'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'Store - Подтверждение электронной почты'
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))

# def login(request):
#     if request.method == 'POST':
#         form = UserLoginForm(data=request.POST)
#         if form.is_valid():
#             username = request.POST['username']
#             password = request.POST['password']
#             user = auth.authenticate(username=username, password=password)
#             if user:
#                 auth.login(request, user)
#                 return HttpResponseRedirect(reverse('index'))
#     else:
#         form = UserLoginForm()
#     context = {'form': form}
#     return render(request, 'users/login.html', context)

# def registration(request):
#     if request.method == 'POST':
#         form = UserRegistrationForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Поздравляем! Вы успешно зарегистрированы!')
#             return HttpResponseRedirect(reverse('users:login'))
#     else:
#         form = UserRegistrationForm()
#     context = {'form': form}
#     return render(request, 'users/registration.html', context)

# @login_required
# def profile(request):
#     if request.method == 'POST':
#         form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('users:profile'))
#     else:
#         form = UserProfileForm(instance=request.user)
#
#     context = {
#         'title': 'Store - Профиль',
#         'form': form,
#         'baskets': Basket.objects.filter(user=request.user),
#     }
#     return render(request, 'users/profile.html', context)

# def logout(request):
#     auth.logout(request)
#     return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}
        
        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/email_verification.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Ваша учетная запись успешно подтверждена!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:login' %}">Продолжить</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load socialaccount %}
{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if messages or form.non_field_errors %}
                        <div class="
                            {% if messages %}
                                alert-success
                            {% else %}
                                alert-warning
                            {% endif %}
                            alert alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:login' %}" method="post">
                                {%  csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Забыли пароль?</a>
                                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a href="#">
                                        <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                    </a>
                                    <a href="{% provider_login_url "github" %}">
                                        <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'products/base.html'%}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="
                        {% if user.image %}
                            {{ user.image.url }}
                        {% else %}
                            {% static 'vendor/img/users/default_avatar.jpg' %}
                        {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                            Имя пользователя
                        </label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                            Адрес электронной почты
                        </label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            {% include 'products/baskets.html' %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {%  if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'users:registration' %}">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                            почты</label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                пароля</label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}